# Generated by Django 4.2.4 on 2023-09-28 16:05
from django.db import migrations


def forwards_func(apps, schema_editor):
    topic = apps.get_model("agency", "Topic")
    newspaper = apps.get_model("agency", "Newspaper")
    redactors = apps.get_model("agency", "Redactor")
    db_alias = schema_editor.connection.alias


def reverse_func(apps, schema_editor):
    topic = apps.get_model("agency", "Topic")
    newspaper = apps.get_model("agency", "Newspapers")
    redactors = apps.get_model("agency", "Redactors")
    db_alias = schema_editor.connection.alias


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
